config/routes.rb
S2k::Application.routes.draw do
	
	root :to => "videos#index"

	devise_for :users, 
		:path_names => { :sign_up => "register" }

	resources :videos
	resources :crews
	resources :bboys
	resources :video_participants

end

app/models/crew.rb
class Crew < ActiveRecord::Base
	has_and_belongs_to_many :bboys
	has_many :video_participants, 
		:class_name => "VideoParticipant",
		:foreign_key => "crew_id"
	has_many :videos, 
		:through => :video_participants,
		:readonly => true

end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  # GET /crews
  # GET /crews.xml
  def index
    @crews = Crew.all.find_all {|c| c.name =~ /#{Regexp.escape(params[:term] ||= "")}/i}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @crews }
      format.xml  { render :xml => @crews }
    end
  end

  # GET /crews/1
  # GET /crews/1.xml
  def show
    @crew = Crew.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @crew }
    end
  end

  # GET /crews/new
  # GET /crews/new.xml
  def new
    @crew = Crew.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @crew }
    end
  end

  # GET /crews/1/edit
  def edit
    @crew = Crew.find(params[:id])
  end

  # POST /crews
  # POST /crews.xml
  def create
    @crew = Crew.new(params[:crew])

    respond_to do |format|
      if @crew.save
        format.html { redirect_to(@crew, :notice => 'Crew was successfully created.') }
        format.xml  { render :xml => @crew, :status => :created, :location => @crew }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @crew.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /crews/1
  # PUT /crews/1.xml
  def update
    @crew = Crew.find(params[:id])

    respond_to do |format|
      if @crew.update_attributes(params[:crew])
        format.html { redirect_to(@crew, :notice => 'Crew was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @crew.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1
  # DELETE /crews/1.xml
  def destroy
    @crew = Crew.find(params[:id])
    @crew.destroy

    respond_to do |format|
      format.html { redirect_to(crews_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/crews/_form.html.erb
<%= form_for(@crew) do |f| %>
  <% if @crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% @crew.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing crew</h1>

<%= render 'form' %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<div class="page-header">
	<h1>Listing crews</h1>
</div>

<div class="row">
	<div class="offset2 span12">
		<table class="bordered-table zebra-striped">
			<tr>
				<th>Name</th>
				<% if user_signed_in? %>
					<th>-</th>
					<th>-</th>
				<% end %>
			</tr>

		<% @crews.each do |crew| %>
			<tr>
				<td><%= link_to crew.name, crew %></td>
				<% if user_signed_in? %>
					<td><%= link_to 'Edit', edit_crew_path(crew) %></td>
					<td><%= link_to 'Destroy', crew, :confirm => 'Are you sure?', :method => :delete %></td>
				<% end %>
			</tr>
		<% end %>
		<tfoot>
			<tr>
				<td><%= link_to '+ Add', new_crew_path %></td>
			</tr>
		</tfoot>
		</table>
	</div>
</div>

<div class="row">
	<div class="offset1 span14">
		<%= link_to 'New Crew', new_crew_path %>
	</div>
</div>

app/views/crews/new.html.erb
<h1>New crew</h1>

<%= render 'form' %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<ul class="breadcrumb">
	<li><%= link_to "Crews", crews_path %><span class="divider">/</span></li>
	<li><%= @crew.name %></li>
</ul>

<div class="page-header">
	<h1><%= @crew.name %></h1>
</div>

<%if(! notice.nil?)%>
<div class="row">
	<div class="span14 offset1">
		<div class="alert-message warning">
  			<a class="close" href="#">×</a>
			<p><%= notice %></p>
		</div>
	</div>
</div>
<% end %>
<div class="row">
	<div class="span14 offset1">



		<h2>Members of <%= @crew.name %></h2>

		<ul>
		<% @crew.bboys.uniq.each do |bboy| %>
			<li><%= link_to bboy.bboyName, bboy %></li>
		<% end %>
		</ul>

		<h2>Videos of <%= @crew.name %></h2>
		<ul>
		<% @crew.videos.uniq.each do |video| %>
			<li><%= link_to video.title, video %></li>
		<% end %>
		</ul>

		<%= link_to 'Edit', edit_crew_path(@crew) if user_signed_in? %>
		<%= link_to 'Back', crews_path %>

	</div>
</div>