config/routes.rb
S2k::Application.routes.draw do
	
	root :to => "videos#index"

	devise_for :users, 
		:path_names => { :sign_up => "register" }

	resources :videos
	resources :crews
	resources :bboys
	resources :video_participants

end

app/models/bboy.rb
class Bboy < ActiveRecord::Base
	has_many :video_participants, 
		:class_name => "VideoParticipant",
		:foreign_key => "bboy_id"
	has_many :videos, 
		:through => :video_participants,
		:readonly => true
	has_and_belongs_to_many :crews
		
	def battled_with
		#vpList = VideoParticipant.find_by_bboy_id(self.id)
		self.video_participants.collect(&:crew).uniq
	end
end

app/controllers/bboys_controller.rb
class BboysController < ApplicationController
	# GET /bboys
	# GET /bboys.xml
	def index
		@bboys = Bboy.all.find_all {|b| b.bboyName =~ /#{Regexp.escape(params[:term] ||= "")}/i}

		respond_to do |format|
			format.html # index.html.erb
			format.json { 
				render :json =>@bboys
			}
			format.xml  { render :xml => @bboys }
		end
	end

	# GET /bboys/1
	# GET /bboys/1.xml
	def show
		@bboy = Bboy.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @bboy }
		end
	end

	# GET /bboys/new
	# GET /bboys/new.xml
	def new
		@bboy = Bboy.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @bboy }
		end
	end

	# GET /bboys/1/edit
	def edit
		@bboy = Bboy.find(params[:id])
	end

	# POST /bboys
	# POST /bboys.xml
	def create
		@bboy = Bboy.new(params[:bboy])

		respond_to do |format|
			if @bboy.save
				format.html { redirect_to(@bboy, :notice => 'Bboy was successfully created.') }
				format.xml  { render :xml => @bboy, :status => :created, :location => @bboy }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @bboy.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /bboys/1
	# PUT /bboys/1.xml
	def update
		@bboy = Bboy.find(params[:id])

		respond_to do |format|
			if @bboy.update_attributes(params[:bboy])
				format.html { redirect_to(@bboy, :notice => 'Bboy was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @bboy.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /bboys/1
	# DELETE /bboys/1.xml
	def destroy
		@bboy = Bboy.find(params[:id])
		@bboy.destroy

		respond_to do |format|
			format.html { redirect_to(bboys_url) }
			format.xml  { head :ok }
		end
	end
end

app/helpers/bboys_helper.rb
module BboysHelper
end

app/views/bboys/_form.html.erb
<%= form_for(@bboy) do |f| %>
  <% if @bboy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bboy.errors.count, "error") %> prohibited this bboy from being saved:</h2>

      <ul>
      <% @bboy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bboyName %><br />
    <%= f.text_field :bboyName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bboys/edit.html.erb
<h1>Editing bboy</h1>

<%= render 'form' %>

<%= link_to 'Show', @bboy %> |
<%= link_to 'Back', bboys_path %>

app/views/bboys/index.html.erb
<div class="page-header">
	<h1>BBoys<small>and their associated crews</small></h1>
</div>
<div class="row">
	<div class="span14 offset1">
		<table id="bboyTable" class="bordered-table zebra-striped">
		<tr>
		<th>Bboy Name</th>
		<th>Crew(s)</th>
		<th></th>
		</tr>

		<% @bboys.each do |bboy| %>
				<tr>
				<td><%= link_to bboy.bboyName, bboy %></td>
				<td><%= bboy.crews.uniq.collect{|c| link_to c.name, c}.to_sentence.html_safe  %></td>
				<td><%= link_to "Edit", edit_bboy_path(bboy) if user_signed_in? %></td>
				</tr>
		<% end %>
		</table>
		<br>
		<%= link_to 'New Bboy', new_bboy_path , :class => "btn primary" if user_signed_in?%>
	</div>
</div>


<script type="text/javascript">
$(function(){
	$("#bboyTable").tablesorter();
});
</script>

app/views/bboys/new.html.erb
<h1>New bboy</h1>

<%= render 'form' %>

<%= link_to 'Back', bboys_path %>

app/views/bboys/show.html.erb
<ul class="breadcrumb">
	<li><%= link_to "BBoys", bboys_path %><span class="divider">/</span></li>
	<li><%= @bboy.bboyName %></li>
</ul>

<div class="page-header">
	<h1>
		<%= @bboy.bboyName %>
		<small>
			<% if(@bboy.crews.count > 0)%>
				(<%= @bboy.crews.uniq.collect{|c| link_to c.name, c}.join(" / ").html_safe %>)
			<% else %>
				<em>Independent</em>
			<% end %>
		</small>
	</h1>
</div>

<%if(! notice.nil?)%>
<div class="row">
	<div class="span14 offset1">
		<div class="alert-message warning">
  			<a class="close" href="#">×</a>
			<p><%= notice %></p>
		</div>
	</div>
</div>
<% end %>

<div class="row">
	<div class="span14 offset1">
		<% if !(@bboy.name.blank?) %>
		<p>
		  <b>Full Name:</b> <%= @bboy.name %>
		</p>
		<% end %>


		<% if @bboy.battled_with.size > 0 %>
			<h3>Has Battled with</h3>
				<%= @bboy.battled_with.collect{|c| link_to c.name, c}.to_sentence.html_safe %>
		<% end %>


		<h3>Videos</h3>
		<% if @bboy.videos.count == 0%>
			<em>None</em>
		<% else %>
			<ul>
				<% @bboy.videos.uniq.each do |video| %>
					<li><%= link_to youtube_thumbnail(video), video%> <%= link_to video.title, video%></li>
				<% end %>
			</ul>
		<% end %>

	</div>
</div>