config/routes.rb
S2k::Application.routes.draw do
	
	root :to => "videos#index"

	devise_for :users, 
		:path_names => { :sign_up => "register" }

	resources :videos
	resources :crews
	resources :bboys
	resources :video_participants

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_many :video_participants, 
		:class_name => "VideoParticipant",
		:foreign_key => "video_id"
	has_many :crews, 
		:through => :video_participants,
		:readonly => true
	has_many :bboys, 
		:through => :video_participants,
		:readonly => true

	def add_participant(bboy, crew)
		if bboy != nil || bboy.id? || crew != nil || crew.id? || video != nil || video.id?
			participant = VideoParticipant.create(:bboy_id => bboy.id, :crew_id => crew.id, :video_id => self.id)
			participant.save
		elsif bboy == nil || crew == nil || video == nil 
			raise ArgumentError, "Video, Bboy and Crew can not be nil " 
		elsif bboy.id? || crew.id? || video.id?
			raise ArgumentError, "Video, Bboy and Crew must have ids" 
		end
	end
	
	def to_html(height=390, width=640)
		return "<iframe 
			class='youtubeFrame'
			title='YouTube video player' 
			width='#{width}' 
			height='#{height}' 
			src='http://www.youtube.com/embed/#{self.youtubeID}' 
			frameborder='0'
			allowfullscreen>
		</iframe>".html_safe
	end

	def crew_hash
		self.video_participants.group_by(&:crew_id)
	end
	
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	# GET /videos
	# GET /videos.xml
	def index
		@videos = Video.all

		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @videos }
			format.json  { render :json => @videos }
		end
	end

	# GET /videos/1
	# GET /videos/1.xml
	def show
		@video = Video.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @video }
		end
	end

	# GET /videos/new
	# GET /videos/new.xml
	def new
		@video = Video.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @video }
		end
	end

	# GET /videos/1/edit
	def edit
		@video = Video.find(params[:id])
	end

	# POST /videos
	# POST /videos.xml
	def create
		@video = Video.new(params[:video])

		respond_to do |format|
			if @video.save
				format.html { redirect_to(@video, :notice => 'Video was successfully created.') }
				format.xml  { render :xml => @video, :status => :created, :location => @video }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /videos/1
	# PUT /videos/1.xml
	def update
		@video = Video.find(params[:id])

		respond_to do |format|
			if @video.update_attributes(params[:video])
				format.html { redirect_to(@video, :notice => 'Video was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /videos/1
	# DELETE /videos/1.xml
	def destroy
		@video = Video.find(params[:id])
		@video.destroy

		respond_to do |format|
			format.html { redirect_to(videos_url) }
			format.xml  { head :ok }
		end
	end
end

app/helpers/videos_helper.rb
module VideosHelper
	def youtube_thumbnail(video)
		 image_tag("http://img.youtube.com/vi/#{video.youtubeID}/0.jpg", :alt => video.title)
	end
end

app/views/videos/_crewList.html.erb
<% crewHash = @video.crew_hash %>
<div class="row">

	<% crewHash.keys.each do |crew_id| %>
	<div class="offset1 span3">
		<dl id="crew<%=crew_id%>" class="bboyList">
		<dt>
			<h4><%= link_to crewHash[crew_id].first.crew.name, crewHash[crew_id].first.crew %></h5>
		</dt>
		<% crewHash[crew_id].each do |vp| %>
			<dd id="bboy<%=vp.id%>" class="bboy">
				<%= link_to vp.bboy.bboyName, bboy_path(vp.bboy)%>
				<% if user_signed_in? %>
				(<%= link_to "remove", video_participant_path(vp), :confirm => "Are you sure they aren't in this video?", :method => :delete, :class => "removeBboy" %>)
				<% end %>
			</dd>
		<% end %>
		</dl>
	</div>
	<% end %>


</div>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :youtubeID %><br />
    <%= f.text_field :youtubeID %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_participantForm.html.erb
<% if user_signed_in? %>
	<h4>Add bboys</h4>
	<%= form_for(VideoParticipant.new) do |f| %>

		<%= label :video_participant, :bboyName %>
		<%= f.text_field :bboy_name %>

		
		<%= label :video_participant, :crew %>
		<%= f.text_field :crew_name %>
		
		<%= hidden_field :video_participant, "video_id", { :value => @video.id}%>
		
		<%= submit_tag "Add" %>
	<% end %>

<script type="text/javascript">  

	$(document).ready(function(){ 

		$("#video_participant_bboy_name").autocomplete({  
			source: function( request, response ) {
				$.ajax({
					url: "<%= bboys_path(:json)%>?term=" + request.term,
					dataType: "json",
					success: function( data ) {
						crewMap = $.map( data, function( item ) {
								return {
									label: item.bboy.bboyName,
									value: item.bboy.bboyName
								}
							});
						response(crewMap);
					}
				});
			}});
		
		$("#video_participant_crew_name").autocomplete({  
			source: function( request, response ) {
				$.ajax({
					url: "<%= crews_path(:json)%>?term=" + request.term,
					dataType: "json",
					success: function( data ) {
						crewMap = $.map( data, function( item ) {
								return {
									label: item.crew.name,
									value: item.crew.name
								}
							});
						response(crewMap);
					}
				});
			}});
	});
</script>  
<% end %>

app/views/videos/_videoList.html.erb
<ul class="videoList">
<% videos.each do |video| %>
	<li>
		<span><%= link_to youtube_thumbnail(video), video %></span>
		<span><%= link_to video.title, video %></span>
		<span><%= video.description %></span>
		<% if user_signed_in? %>
			<span><%= link_to 'Edit', edit_video_path(video) %></span>
			<span><%= link_to 'Destroy', video, :confirm => 'Are you sure?', :method => :delete %></span>
		<% end %>
	</li>
<% end %>
</ul>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Featured Videos</h1>

<%= render :partial => 'videoList', :locals => { :videos => @videos} %>

<br />

<%= link_to 'New Video', new_video_path if user_signed_in? %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<% content_for :head do %>
	<meta property="og:title" content="<%=h @video.title %>"/>
	<meta property="og:description" content="<%=h @video.description %>"/>

	<meta property="og:type" content="video"/>
	<meta property="og:video" content="http://www.youtube.com/v/<%=@video.youtubeID%>?version=3&amp;autohide=1" />
	<meta property="og:video:height" content="390" />
	<meta property="og:video:width" content="640" />
	<meta property="og:video:type" content="application/x-shockwave-flash" />
	<meta property="og:image" content="http://img.youtube.com/vi/<%=@video.youtubeID%>/1.jpg"/>
<% end %>

<div class="page-header">
	<h1><%= @video.title %></h1>
</div>

<div class="row">
	<div class="offset2 span8">
		<p id="notice"><%= notice %></p>
	</div>
</div>

<div id="videoContainer" class="row">
	<div class="offset1 span14">
		<%= @video.to_html(488, 800) %>
	</div>
</div>

<div id="videoDescription" class="row">
	<div class="offset1 span8">
		<h2>Description:</h2>
		<div >
			<p><%= @video.description %></p>
		</div>
	</div>
	<div class="offset1 span6">
		<div id="likeButton">
			<%= facebook_like %>
		</div>
	</div>
</div>

<div class="row">
	<div class="offset1 span14">
		<h3>Crews</h3>
	</div>
</div>

<%= render "crewList" %>

<div class="row">
	<div class="span16">
		<%= render "participantForm", :locals => { :video => @video } %>
	</div>
	<%= link_to "Edit", edit_video_path(@video) if user_signed_in? %>
</div>
