config/routes.rb
S2k::Application.routes.draw do
	
	root :to => "videos#index"

	devise_for :users, 
		:path_names => { :sign_up => "register" }

	resources :videos
	resources :crews
	resources :bboys
	resources :video_participants

end

app/views/1111_video_participants/_form.html.erb
<%= form_for(@video_participant) do |f| %>
  <% if @video_participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video_participant.errors.count, "error") %> prohibited this video_participant from being saved:</h2>

      <ul>
      <% @video_participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bboy_id %><br />
    <%= f.text_field :bboy_id %>
  </div>
  <div class="field">
    <%= f.label :video_id %><br />
    <%= f.text_field :video_id %>
  </div>
  <div class="field">
    <%= f.label :crew_id %><br />
    <%= f.text_field :crew_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/1111_video_participants/edit.html.erb
<h1>Editing video_participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @video_participant %> |
<%= link_to 'Back', video_participants_path %>

app/views/1111_video_participants/index.html.erb
<h1>Listing video_participants</h1>

<table>
  <tr>
    <th>Bboy</th>
    <th>Video</th>
    <th>Crew</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @video_participants.each do |video_participant| %>
  <tr>
    <td><%= video_participant.bboy_id %></td>
    <td><%= video_participant.video_id %></td>
    <td><%= video_participant.crew_id %></td>
    <td><%= link_to 'Show', video_participant %></td>
    <td><%= link_to 'Edit', edit_video_participant_path(video_participant) %></td>
    <td><%= link_to 'Destroy', video_participant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video participant', new_video_participant_path %>

app/views/1111_video_participants/new.html.erb
<h1>New video_participant</h1>

<%= render 'form' %>

<%= link_to 'Back', video_participants_path %>

app/views/1111_video_participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bboy:</b>
  <%= @video_participant.bboy_id %>
</p>

<p>
  <b>Video:</b>
  <%= @video_participant.video_id %>
</p>

<p>
  <b>Crew:</b>
  <%= @video_participant.crew_id %>
</p>


<%= link_to 'Edit', edit_video_participant_path(@video_participant) %> |
<%= link_to 'Back', video_participants_path %>